//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegurosSigloXXI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adicciones
    {
        public Adicciones()
        {
            this.Mantenimiento_Adicciones_Cliente = new HashSet<Mantenimiento_Adicciones_Cliente>();
        }
    
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public int ID_ADICCION { get; set; }
    
        public virtual ICollection<Mantenimiento_Adicciones_Cliente> Mantenimiento_Adicciones_Cliente { get; set; }
    }
}
