//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegurosSigloXXI
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string correo_electronico { get; set; }
        public Nullable<int> contrasena_cedula { get; set; }
        public string tipo { get; set; }
        public short id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_sesion { get; set; }
    }
}
